### ISSUE TITLE
[Feature] Not having to switch remote app folders

### ISSUE THREAD

**Issue by xghrtkl** [LightningMods/Itemzflow#14]
Is there any work around for not to rename the game folder to "app" every time I change the game? ie: every time I want to play a new game I need to change the dump folder (ie: CUSAXXXX) to "app" folder in order for the Itemzflow remote app to working

**Comment by xghrtkl** [comment]
>>What I can think of as the temp solution is creating a bat script file that will delete (if any files exist before) files on app folder , then copy paste the content of the CUSAXXXX files that I want to play into the app folder

But my next question, since I have multiple PS4 on my house and we sometimes use it in the same time, what if another PS4 want to play another games? 
>>Can I set a different sharing folder for each of the PS4? ie: C:\Users\DELL\Downloads\PS1\app and C:\Users\DELL\Downloads\**PS2**\app, while I will store all of the games in C:\Users\DELL\Downloads\**Games**, and using the bat file I created earlier, each of the PS4 player can setup what games they want to play by running & selecting the games, so the bat file will copy paste files to the app folder? Is it make sense? do you think it will work?

**Comment by LightningMods** [comment]
not yet but I might add another option in the future for that

**Comment by LightningMods** [comment]
This feature has been added to the new 1.06 update just released
