### ISSUE TITLE
Any way to run FUSE on PS4 6.72?

### ISSUE THREAD

**Issue by rikuddo91** [LightningMods/Itemzflow#15]
Tried mounting the folder with Winfsp but it simply shows an empty folder on PS4, even though there's a pkg file in the folder on PC.

After spending a day, I read the changelog and there it states, 

> 'Fuse currently only supports 9.00 and 5.05 goldhen'

I guess, it's a limitation by app currently, if so, is there any plan to extent the support to 6.72 version?

Here are the log files from PS4

[libfuse.log](https://github.com/LightningMods/Itemzflow/files/11712344/libfuse.log)
[daemon.log](https://github.com/LightningMods/Itemzflow/files/11712345/daemon.log)
[fuse_ip.txt](https://github.com/LightningMods/Itemzflow/files/11712346/fuse_ip.txt)

Here's the WinFSP output on Windows 10,

``` .\WinNFSd.exe E:\pkgdl /
=====================================================
WinNFSd 2.4.0 [5f7f224]
Network File System server for Windows
Copyright (C) 2005 Ming-Yang Kao
Edited in 2011 by ZeWaren
Edited in 2013 by Alexander Schneider (Jankowfsky AG)
Edited in 2014 2015 by Yann Schepens
Edited in 2016 by Peter Philipp (Cando Image GmbH), Marc Harding
=====================================================
Path #1 is: E:\pkgdl, path alias is: /
Portmap daemon started
NFS daemon started
Mount daemon started
Listening on 0.0.0.0
Type 'help' to see help

PORTMAP NULL
PORTMAP GETPORT 100005 1058
MOUNT NULL
MOUNT MNT from 192.168.0.112
Final local requested path: \\?\E:\pkgdl

MOUNT EXPORT
MOUNT MNT from 192.168.0.112
Final local requested path: \\?\E:\pkgdl

PORTMAP NULL
PORTMAP GETPORT 100003 2049
[13:30:59] NFS NULL
[13:30:59] NFS FSINFO \\?\E:\pkgdl
[13:30:59] NFS GETATTR \\?\E:\pkgdl
[13:30:59] NFS GETATTR \\?\E:\pkgdl ```

**Comment by LightningMods** [comment]
yes, fuse currently doesn't work on 6.72 because it's missing patches for 6.72 which is why its not working for you, normally there is a dialogue message that tells you that its not supported however if you used a spoofer or used a version of goldhen that spoofs your firmware then you might not see that message, I do currently have a dev build of Itemzflow with the required 6.72 patches (I think it worked when we tested it)

if you want to test it let me know

**Comment by rikuddo91** [comment]
> yes, fuse currently doesn't work on 6.72 because it's missing patches for 6.72 which is why its not working for you, normally there is a dialogue message that tells you that its not supported however if you used a spoofer or used a version of goldhen that spoofs your firmware then you might not see that message, I do currently have a dev build of Itemzflow with the required 6.72 patches (I think it worked when we tested it)
> 
> if you want to test it let me know

Thanks for the reply. Yes, I was using Goldhen, and I think the spoofer might've been on too.

I'd love to test that build.

**Comment by LightningMods** [comment]
here's the build to test (link will expire in 10 mins)
https://justbeamit.com/vyenb

**Comment by rikuddo91** [comment]
> here's the build to test (link will expire in 10 mins) https://justbeamit.com/vyenb

Got it. Thanks. I'll test it and let you know if I encounter any issue.
If you want me to test anything in particular then let me know that too.

**Comment by LightningMods** [comment]
Not anything in particular other than installing a pkg via nfs/fuse, if you face any crashes while testing its because of the new features i'm still adding and/or fixing

**Comment by rikuddo91** [comment]
> Not anything in particular other than installing a pkg via nfs/fuse, if you face any crashes while testing its because of the new features i'm still adding and/or fixing

Just using fuse. Working flawlessly so far. 
One thing I noticed was, that while moving between menus in 'Options', there's a tiny lag each time. Even the background menu lag when I move from one option to another.
 
FUSE is working perfectly well though. I also love that the 'PKG Installer' menu automatically default to root directory now, so you can immediately go to 'hostapp' folder. It's small change but very much appreciated.

**Comment by LightningMods** [comment]
Since it now works on 6.72 I'm closing this issue
