### ISSUE TITLE
[Feature] Batch Install FPKGs

### ISSUE THREAD

**Issue by Sora1995** [LightningMods/Itemzflow#22]
Love the app! Is it possible to batch install FPGK's, especially on the NFS folder? Having to do it one by one with such large files is time consuming. Having just one button to press to either install all or the option to select multiple and install them back to back would be a godsend. Thank you!

**Comment by LightningMods** [comment]
Hello, yes we have already made this feature for the next Itemzflow update , The new feature installs all the pkgs in that folder (not recursive) and shows the install progress for each PKG, if you want you can test it
![My_Great_Game_-_My_Great_Capture_2023-02-19_18-40-16](https://github.com/LightningMods/Itemzflow/assets/34066913/571617c8-88ce-46da-9902-7d6d63b50d74)

**Comment by Sora1995** [comment]
That would be great! Thanks!

**Comment by LightningMods** [comment]
@Sora1995 try this PKG
https://github.com/LightningMods/Itemzflow/issues/21#issuecomment-1751612210

**Comment by Sora1995** [comment]
> @Sora1995 try this PKG
> https://github.com/LightningMods/Itemzflow/issues/21#issuecomment-1751612210

It does work! But it seems the app is crashing

**Comment by LightningMods** [comment]
@Sora1995 yes the app might crash doing certain things as its a test build whats important is that the feature you want works
