### ISSUE TITLE
ERROR: Network Share failed to connect check your connection and try again 

### ISSUE THREAD

**Issue by iceMongus** [LightningMods/Itemzflow#23]
TrueNAS Scale server with IP 10.10.1.201... NFS share with setting 'Allow non-root mount' and user 'nfs-share' without password
share folder: '/mnt/GaminG/6Tb/PlayStation/PS4/Packages/'

on Linux with 10.10.1.15 in Dolphin File Manager full access without any problem in nfs://10.10.1.201/mnt/GaminG/6Tb/PlayStation/PS4/Packages/

on PlayStation 4 PRO with IP 10.10.1.50 
ItemzFlow Settings>Fuse NFS IP --> nfs://10.10.1.201/mnt/GaminG/6Tb/PlayStation/PS4/Packages/
                            ERROR: Network Share failed to connect check your connection and try again
                            ret:243

play station is in the same network and have accsess to all
here is the part from log file itemzflow_app.log

2023-10-13 22:00:52 DEBUG source/ipc.cpp:73:  IPC Connected via Domain Socket
2023-10-13 22:00:52 DEBUG source/ipc.cpp:75:  Sending IPC Command
2023-10-13 22:00:52 DEBUG source/ipc.cpp:77:  Sent IPC Command 9
2023-10-13 22:00:52 DEBUG source/ipc.cpp:96:  Got message with Size: 1 from Daemon
2023-10-13 22:00:52 DEBUG source/ipc.cpp:103: [ItemzDaemon] Daemon IPC Response: , code: NO_ERROR, readSize: 1
2023-10-13 22:00:52 DEBUG source/ipc.cpp:73:  IPC Connected via Domain Socket
2023-10-13 22:00:52 DEBUG source/ipc.cpp:75:  Sending IPC Command
2023-10-13 22:00:52 DEBUG source/ipc.cpp:77:  Sent IPC Command 11
2023-10-13 22:00:52 DEBUG source/ipc.cpp:96:  Got message with Size: 1 from Daemon
2023-10-13 22:00:52 DEBUG source/ipc.cpp:103: [ItemzDaemon] Daemon IPC Response: , code: Other, readSize: 1
2023-10-13 22:00:52 ERROR source/ipc.cpp:144: FUSE failed to start with error code: 243
2023-10-13 22:00:55 INFO  source/main.cpp:296: Cross pressed
2023-10-13 22:00:55 INFO  source/GLES2_itemzflow.cpp:1169: execute setting 7 -> 'Fuse NFS IP' for 'ItemzCore'
2023-10-13 22:01:06 INFO  source/utils.cpp:1091: status 2, endstatus 0 
2023-10-13 22:01:06 INFO  source/utils.cpp:1099: User Entered text.. Entering into buffer

**Comment by abassi94** [comment]
> TrueNAS Scale server with IP 10.10.1.201... NFS share with setting 'Allow non-root mount' and user 'nfs-share' without password share folder: '/mnt/GaminG/6Tb/PlayStation/PS4/Packages/'
> 
> on Linux with 10.10.1.15 in Dolphin File Manager full access without any problem in nfs://10.10.1.201/mnt/GaminG/6Tb/PlayStation/PS4/Packages/
> 
> on PlayStation 4 PRO with IP 10.10.1.50 ItemzFlow Settings>Fuse NFS IP --> nfs://10.10.1.201/mnt/GaminG/6Tb/PlayStation/PS4/Packages/ ERROR: Network Share failed to connect check your connection and try again ret:243
> 
> play station is in the same network and have accsess to all here is the part from log file itemzflow_app.log
> 
> 2023-10-13 22:00:52 DEBUG source/ipc.cpp:73: IPC Connected via Domain Socket 2023-10-13 22:00:52 DEBUG source/ipc.cpp:75: Sending IPC Command 2023-10-13 22:00:52 DEBUG source/ipc.cpp:77: Sent IPC Command 9 2023-10-13 22:00:52 DEBUG source/ipc.cpp:96: Got message with Size: 1 from Daemon 2023-10-13 22:00:52 DEBUG source/ipc.cpp:103: [ItemzDaemon] Daemon IPC Response: , code: NO_ERROR, readSize: 1 2023-10-13 22:00:52 DEBUG source/ipc.cpp:73: IPC Connected via Domain Socket 2023-10-13 22:00:52 DEBUG source/ipc.cpp:75: Sending IPC Command 2023-10-13 22:00:52 DEBUG source/ipc.cpp:77: Sent IPC Command 11 2023-10-13 22:00:52 DEBUG source/ipc.cpp:96: Got message with Size: 1 from Daemon 2023-10-13 22:00:52 DEBUG source/ipc.cpp:103: [ItemzDaemon] Daemon IPC Response: , code: Other, readSize: 1 2023-10-13 22:00:52 ERROR source/ipc.cpp:144: FUSE failed to start with error code: 243 2023-10-13 22:00:55 INFO source/main.cpp:296: Cross pressed 2023-10-13 22:00:55 INFO source/GLES2_itemzflow.cpp:1169: execute setting 7 -> 'Fuse NFS IP' for 'ItemzCore' 2023-10-13 22:01:06 INFO source/utils.cpp:1091: status 2, endstatus 0 2023-10-13 22:01:06 INFO source/utils.cpp:1099: User Entered text.. Entering into buffer

same issue

**Comment by abassi94** [comment]
> TrueNAS Scale server with IP 10.10.1.201... NFS share with setting 'Allow non-root mount' and user 'nfs-share' without password share folder: '/mnt/GaminG/6Tb/PlayStation/PS4/Packages/'
> 
> on Linux with 10.10.1.15 in Dolphin File Manager full access without any problem in nfs://10.10.1.201/mnt/GaminG/6Tb/PlayStation/PS4/Packages/
> 
> on PlayStation 4 PRO with IP 10.10.1.50 ItemzFlow Settings>Fuse NFS IP --> nfs://10.10.1.201/mnt/GaminG/6Tb/PlayStation/PS4/Packages/ ERROR: Network Share failed to connect check your connection and try again ret:243
> 
> play station is in the same network and have accsess to all here is the part from log file itemzflow_app.log
> 
> 2023-10-13 22:00:52 DEBUG source/ipc.cpp:73: IPC Connected via Domain Socket 2023-10-13 22:00:52 DEBUG source/ipc.cpp:75: Sending IPC Command 2023-10-13 22:00:52 DEBUG source/ipc.cpp:77: Sent IPC Command 9 2023-10-13 22:00:52 DEBUG source/ipc.cpp:96: Got message with Size: 1 from Daemon 2023-10-13 22:00:52 DEBUG source/ipc.cpp:103: [ItemzDaemon] Daemon IPC Response: , code: NO_ERROR, readSize: 1 2023-10-13 22:00:52 DEBUG source/ipc.cpp:73: IPC Connected via Domain Socket 2023-10-13 22:00:52 DEBUG source/ipc.cpp:75: Sending IPC Command 2023-10-13 22:00:52 DEBUG source/ipc.cpp:77: Sent IPC Command 11 2023-10-13 22:00:52 DEBUG source/ipc.cpp:96: Got message with Size: 1 from Daemon 2023-10-13 22:00:52 DEBUG source/ipc.cpp:103: [ItemzDaemon] Daemon IPC Response: , code: Other, readSize: 1 2023-10-13 22:00:52 ERROR source/ipc.cpp:144: FUSE failed to start with error code: 243 2023-10-13 22:00:55 INFO source/main.cpp:296: Cross pressed 2023-10-13 22:00:55 INFO source/GLES2_itemzflow.cpp:1169: execute setting 7 -> 'Fuse NFS IP' for 'ItemzCore' 2023-10-13 22:01:06 INFO source/utils.cpp:1091: status 2, endstatus 0 2023-10-13 22:01:06 INFO source/utils.cpp:1099: User Entered text.. Entering into buffer

found Soultion just set the ip to nfs://10.0.0.248/mnt/ima2/stock/hdd/drive1/2x
