### ISSUE TITLE
I got strooooke

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [LightningMods/Itemzflow#26]
I can't mount any game, and when i unplug my usb hdd my ps5 just restarts
Idk it's because of the new etahen and itemzflow, or is it because i copied a game to internal storage

[PS5][INFO]: [SQLITE][sqlite3_os_init]SQLite for Orbis
[PS5][INFO]: [SQLITE][
sqlite3_os_init]Registering vfs
[PS5][ERROR]: parser: [[[PRAGMA journal_mode = OFF;]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "PRAGMA journal_mode = OFF;"
[PS5][ERROR]: sParse.rc 26
[PS5][ERROR]: parser: [[[SELECT TID, Title, GM_PATH FROM itemzflow_ps5_games;]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "SELECT TID, Title, GM_PATH FROM itemzflow_ps5_games;"
[PS5][ERROR]: sParse.rc 26
[PS5][ERROR]: parser: [[[PRAGMA journal_mode = OFF;]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "PRAGMA journal_mode = OFF;"
[PS5][ERROR]: sParse.rc 26
[PS5][ERROR]: parser: [[[SELECT TID, Title, GM_PATH FROM itemzflow_ps5_games;]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "SELECT TID, Title, GM_PATH FROM itemzflow_ps5_games;"
[PS5][ERROR]: sParse.rc 26
[PS5][ERROR]: parser: [[[PRAGMA journal_mode = OFF;]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "PRAGMA journal_mode = OFF;"
[PS5][ERROR]: sParse.rc 26
[PS5][ERROR]: parser: [[[INSERT OR REPLACE INTO itemzflow_ps5_games (TID, Title, GM_PATH) VALUES ('PPSA05132', 'Sifu', '/mnt/usb0/PS5/Sifu PS5 Dump v1.006');]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "INSERT OR REPLACE INTO itemzflow_ps5_games (TID, Title, GM_PATH) VALUES ('PPSA05132', 'Sifu', '/mnt/usb0/PS5/Sifu PS5 Dump v1.006');"
[PS5][ERROR]: sParse.rc 26
[PS5][ERROR]: parser: [[[PRAGMA journal_mode = OFF;]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "PRAGMA journal_mode = OFF;"
[PS5][ERROR]: sParse.rc 26
[PS5][ERROR]: parser: [[[INSERT OR REPLACE INTO itemzflow_ps5_games (TID, Title, GM_PATH) VALUES ('PPSA02225', 'Ghost of Tsushima', '/data/GAME/PPSA02225-app0');]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: parser: [[[CREATE TABLE x(type text,name text,tbl_name text,rootpage int,sql text)]]]
[PS5][ERROR]: sqlite3ParserInit pParse->rc 0
[PS5][ERROR]: sParse.rc 0
[PS5][ERROR]: pzErrMsg!=0 file is not a database in "INSERT OR REPLACE INTO itemzflow_ps5_games (TID, Title, GM_PATH) VALUES ('PPSA02225', 'Ghost of Tsushima', '/data/GAME/PPSA02225-app0');"
[PS5][ERROR]: sParse.rc 26

**Comment by TheOneEyedGrimReaper** [comment]
Update:
I reinstalled the previous version of itemzflow and sended etahen 1.2b payload and works again.
So there's some problems with itemzflow 1.4 or the etahen 1.3b

**Comment by LightningMods** [comment]
can you send the full log
