### ISSUE TITLE
Game dir has failed to change

### ISSUE THREAD

**Issue by Kudg3** [LightningMods/Itemzflow#27]
Hello, Thank you for all the work you have done. 

I keep getting the dir has failed to change when selecting the game to start in itemzflow. I am runnung 4.50 and using the latest etahen.  Im sure there is something im missing.

**Comment by Kudg3** [comment]
[itemzflow_app log.txt](https://github.com/LightningMods/Itemzflow/files/13877801/itemzflow_app.log.txt)

**Comment by LightningMods** [comment]
try witt the latest itemzflow and etahen then tell me if you are having the same issue
