### ISSUE TITLE
black screen ps4

### ISSUE THREAD

**Issue by Metalomeus** [LightningMods/Itemzflow#30]
After updating to 1.05 from 1.03 is takes 5 to 10 mins to load the UI.....but it's completely unresponsive.....

**Comment by Doyle4** [comment]
Sounds like same issue as me.

Mr Lightning mods said this to me so Id suggest also doing the same.

"Hello, send me this log and ill look into it
/user/app/ITEM00001/logs/itemzflow_app.log"

**Comment by Metalomeus** [comment]
> Sounds like same issue as me.
> 
> Mr Lightning mods said this to me so Id suggest also doing the same.
> 
> "Hello, send me this log and ill look into it /user/app/ITEM00001/logs/itemzflow_app.log"

Ok ....I will do....thx

**Comment by LightningMods** [comment]
@Metalomeus try this PKG
[IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016175/IV0002-ITEM00001_00-STOREUPD00000000.zip)

**Comment by Metalomeus** [comment]
> @Metalomeus try this PKG [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016175/IV0002-ITEM00001_00-STOREUPD00000000.zip)]

[itemzflow_app.log](https://github.com/LightningMods/Itemzflow/files/14016280/itemzflow_app.log)
[loader.log](https://github.com/LightningMods/Itemzflow/files/14016281/loader.log)

My logs from old install

I did a fresh install of the new PKG.
I've been asked to DL covers....I said no.
After 2 minutes Preloading covers comes up...stuck at 0% for 3 minutes...loads to 87% than black screen again. After 2 min ui loads but is unusable... I got debug FPS around 1 to 2 FPS and debug time is at 700ms....can't navigate the UI but can exit itemzflow without error.. hope this helps

**Comment by LightningMods** [comment]
@Metalomeus are you sure you tested the new PKG? because the new one doesnt have debug MS or anything and also that log says it was compiled yesterday and not today

**Comment by Metalomeus** [comment]
> @Metalomeus are you sure you tested the new PKG? because the new one doesnt have debug MS

[itemzflow_app.log](https://github.com/LightningMods/Itemzflow/files/14016385/itemzflow_app.log)
[loader.log](https://github.com/LightningMods/Itemzflow/files/14016386/loader.log)

Sorry ...these are the logs of the new PKG you gave me....

**Comment by LightningMods** [comment]
@Metalomeus try this PKG
[IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016404/IV0002-ITEM00001_00-STOREUPD00000000.zip)

**Comment by Metalomeus** [comment]
> @Metalomeus try this PKG [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016404/IV0002-ITEM00001_00-STOREUPD00000000.zip)

Fresh install

Same behaviour at boot.

[itemzflow_app.log](https://github.com/LightningMods/Itemzflow/files/14016437/itemzflow_app.log)
[loader.log](https://github.com/LightningMods/Itemzflow/files/14016438/loader.log)

**Comment by LightningMods** [comment]
[IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016518/IV0002-ITEM00001_00-STOREUPD00000000.zip)
the issue is I didnt change very much from the old build so I have to figure out why this build doesnt work for you meanwhile It worked fine for me when I tested it on my 5.05 PS4 downloaded it straight the store app

**Comment by Metalomeus** [comment]
> [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016518/IV0002-ITEM00001_00-STOREUPD00000000.zip) the issue is I didnt change very much from the old build so I have to figure out why this build doesnt work for you meanwhile It worked fine for me when I tested it on my 5.05 PS4 downloaded it straight the store app

I have to mention my PS4 is 9.00... but thank you for your efforts

**Comment by Metalomeus** [comment]
> > [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016518/IV0002-ITEM00001_00-STOREUPD00000000.zip) the issue is I didnt change very much from the old build so I have to figure out why this build doesnt work for you meanwhile It worked fine for me when I tested it on my 5.05 PS4 downloaded it straight the store app
> 
> I have to mention my PS4 is 9.00... but thank you for your efforts
> 
> Update... It works again ....thank you so much

**Comment by LightningMods** [comment]
heres a new PKG that should give a blackscreen like before but with more logs to narrow down whats causing the issue
[IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016585/IV0002-ITEM00001_00-STOREUPD00000000.zip)

**Comment by Metalomeus** [comment]
> heres a new PKG that should give a blackscreen like before but with more logs to narrow down whats causing the issue [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016585/IV0002-ITEM00001_00-STOREUPD00000000.zip)

Again... Fresh install 😄

Logs

[itemzflow_app.log](https://github.com/LightningMods/Itemzflow/files/14016702/itemzflow_app.log)
[loader.log](https://github.com/LightningMods/Itemzflow/files/14016703/loader.log)

**Comment by LightningMods** [comment]
@Metalomeus hopefully this will be the last PKG
[IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016782/IV0002-ITEM00001_00-STOREUPD00000000.zip)

**Comment by Doyle4** [comment]
> @Metalomeus hopefully this will be the last PKG [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016782/IV0002-ITEM00001_00-STOREUPD00000000.zip)

Will give this an install tomorrow and let you know also.

My PS4 is a Phat 9.00, so will report back.

**Comment by Metalomeus** [comment]
> @Metalomeus hopefully this will be the last PKG [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016782/IV0002-ITEM00001_00-STOREUPD00000000.zip)

Yeah.... it's a little late here 1:45 😄

ATM I copy a 45gb PKG to my external drive with itemzflow....after it is finished ....I install the PKG and send you the logs immediately... I hope I'm not the only one here 🤣

**Comment by RetrogamerX** [comment]
Thank you LM

**Comment by Doyle4** [comment]
Installed **IV0002-ITEM00001_00-STOREUPD00000000.zip** all working as expected.

Spotted this version is **1.03** and **not 1.05** so just making sure that is correct.
Also spotted the icon for this version is correct, where as 1.05 on PS4, the icon looked zoomed in and cropped (top of game case covers only shown)

Any more testing etc need doing let me know.

**Comment by RetrogamerX** [comment]
Is this fixed?  

> @Metalomeus hopefully this will be the last PKG [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016782/IV0002-ITEM00001_00-STOREUPD00000000.zip)

Is this fixed now?  Is pkg-zone and Homebrew store itemzflow PS4 versions working?   Im using your version here, but it asks me to download covers ever time I open itemzflow?  I don't remember it doing that before?

**Comment by Metalomeus** [comment]
> Is this fixed?
> 
> > @Metalomeus hopefully this will be the last PKG [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/LightningMods/Itemzflow/files/14016782/IV0002-ITEM00001_00-STOREUPD00000000.zip)
> 
> Is this fixed now? Is pkg-zone and Homebrew store itemzflow PS4 versions working? Im using your version here, but it asks me to download covers ever time I open itemzflow? I don't remember it doing that before?

Just say no and it proceeds further

**Comment by Metalomeus** [comment]
> @RetrogamerX @Metalomeus I have updated the PKG on the Store let me know if you have any issues with the new PKG, ill wait a few hours before announcing the new updated PKG to be sure theres not any more issues https://pkg-zone.com/details/ITEM00001

That's good news...because the PKG I received stopped working again.....thank you

**Comment by Metalomeus** [comment]
![IMG_20240123_211706](https://github.com/LightningMods/Itemzflow/assets/71162300/cd95dbfe-37e5-47cf-9041-fedfe583bce8)

Not working....

**Comment by LightningMods** [comment]
I'm fixing that now also the release date only mentions when it was first released not when it was uploaded

**Comment by Metalomeus** [comment]
> I'm fixing that now also the release date only mentions when it was first released not when it was uploaded

Alles klar 👍

**Comment by LightningMods** [comment]
@Metalomeus try it now

**Comment by Metalomeus** [comment]
> @Metalomeus try it now

Install went fine.....UI load ok.....I see it's 1.4v
Otherwise it's all ok ATM. I have to fiddle around and will report back. Thank you ! Danke....

**Comment by RetrogamerX** [comment]
> > @Metalomeus try it now
> 
> Install went fine.....UI load ok.....I see it's 1.4v Otherwise it's all ok ATM. I have to fiddle around and will report back. Thank you ! Danke....

Which one works now? Do you have a link?

**Comment by Metalomeus** [comment]
> All working fine my end also.

Yes....it seems all is sorted out.... They did good work
