### ISSUE TITLE
No longer launches (PS4)

### ISSUE THREAD

**Issue by Doyle4** [LightningMods/Itemzflow#31]
Was working fine, 10mins ago got an update request, updated, now when it launches my PS4 stays on a black screen, sometimes crashes the PS4.

**Comment by LightningMods** [comment]
Hello, send me this log and ill look into it

**Comment by Doyle4** [comment]
Thanks for reply.
PS4 Is currently powered off at the moment, most likely be tomorrow now I can get a log for you, need to update it again as I downgraded it for it to work again.
Thanks again

**Comment by Doyle4** [comment]
Installed IV0002-ITEM00001_00-STOREUPD00000000.zip all working as expected.

Spotted this version is 1.03 and not 1.05 so just making sure that is correct.
Also spotted the icon for this version is correct, where as 1.05 on PS4, the icon looked zoomed in and cropped (top of game case covers only shown)

Any more testing etc need doing let me know.

**Comment by LightningMods** [comment]
I have updated the PKG on the Store let me know if you have any issues with the new PKG, ill wait a few hours before announcing the new updated PKG to be sure theres not any more issues
https://pkg-zone.com/details/ITEM00001

**Comment by LightningMods** [comment]
the new version has been released and this will now be closed
https://x.com/LightningMods_/status/1749945458787582272?s=20
