### ISSUE TITLE
[Issue] Hard Drive looks like "encrypted"

### ISSUE THREAD

**Issue by DavidBabel** [LightningMods/Itemzflow#33]
First it's worth mentioning that I have 2 identicals USB3 HD.
The first one work like a charm. Never had an issue.

The second one has exactly the same setup (exFat) and every same options on OS inspections. but seems not to work with **Itemzflow** on the PS5 and looks like it is encrypted :

![IMG_0492](https://github.com/LightningMods/Itemzflow/assets/5599375/1680a8cb-411d-4129-a1bb-4bb8f9b4706e)

**Comment by LightningMods** [comment]
That's very strange, I have never seen that before can you send me the itemzflow_app.log from the Itemzflow folder on your USB or from the internal app directory

**Comment by DavidBabel** [comment]
Okay, after further investigation it was not Itemflowz related.
It drove me nuts a bit TBO.

For the Googlers, the issue came from the Disk itself which use to be an Hard Drive dedicated to XBox360.
Regardless the Multiple formating on Windows / Mac, in any file system (exFat) the issue was the low level of the HD needed a hard reset of the partition table. (https://www.startech.com/en-eu/faq/mbr-vs-gpt)

Here is how to do on Windows : 
Open a cmd.exe and type `diskpart`, then follow this command until `clean` : 
![image](https://github.com/LightningMods/Itemzflow/assets/5599375/05ca8dc4-83c4-4112-b9c4-953837e7f94f)

Once done, you will have to recreate the partition table which is kind of like a "factory reset" of the HD. To do so you need to go to the "Disk manager" of windows and Initialize your disk : 
![image](https://github.com/LightningMods/Itemzflow/assets/5599375/01737f10-7944-46c3-887e-8c93769f9518)

I picked GPT, maybe both works, and the HD now is properly recognize by the PS5 and visible in Itemflowz
