### ISSUE TITLE
Customize category for specific items

### ISSUE THREAD

**Issue by JimZiii** [LightningMods/Itemzflow#34]
Currently some homebrews are detected as games so there's no category that only shows games. is it possible to edit the tag itemzflow uses to automatically sort items into categories so that i can edit those few apps to get rid of them from the games category?

If not, maybe you could add this feature?

**Comment by LightningMods** [comment]
I'm closing this issue to to inactivity

**Comment by JimZiii** [comment]
@LightningMods hey, i apologize, haven't been logged for a while and missed your reply.
But here it is
![20240318_022036](https://github.com/LightningMods/Itemzflow/assets/7854537/e7a68840-4535-4f2e-96f0-96197102eea7)
These are the only homebrews visible in games:
- PS4 Temperature
- PS4 Toolset
- PS4-Xplorer 2.0
- Icon Mask


---
A bit off topic but might as well mention it while i got your ear. Currently there's two "no category" selections. One is called "showing category - none" and if you keep pressing square that text at the bottom of the screen disappears completely and you get a popup/notification telling you no category is selected, same as if you press L2 to clear category.
They both show all content.
