### ISSUE TITLE
Can't dump PS4 DLC on PS5

### ISSUE THREAD

**Issue by ccfman2004** [LightningMods/Itemzflow#36]
The current 1.06 version of Itemzflow does not dump any installed DLC for PS4 games. The content does show up in an FTP client but since using FTP doesn't show all files for a currently open game like most files in the sce_sys folders I have no way of knowing if there are any missing files in those DLC. 

Unfortunately I cannot try to use Itemzflow on my 9.00 PS4 for this game as it's not my primary PS4. My 4.50 PS5 is active.

**Comment by ccfman2004** [comment]
If you need any help testing this let me know. I have got tons of PS4 DLC that's activated on my 4.51 PS5.

**Comment by LightningMods** [comment]
After I'm done with all the PS4 things I might have you test the new dumper with new etaHEN

**Comment by ccfman2004** [comment]
Let me know.

**Comment by ccfman2004** [comment]
I saw your tweet about etaHEN 1.8. Need me to test anything?

**Comment by LightningMods** [comment]
Hopefully soon, ill let you know

**Comment by ccfman2004** [comment]
Sounds good.

**Comment by LightningMods** [comment]
hello, Im beginning to add DLC dumping support, if you haven't already join the PKG-Zone discord https://discord.gg/sEH4yrP2, after you join let me know and ill invite you to a private PS5 Testing channel where you can test the new dumper

**Comment by ccfman2004** [comment]
I think I joined but I don’t use Discord so I don’t know what to do. chuckthetekkie.

**Comment by LightningMods** [comment]
sure what is the name you joined under

**Comment by LightningMods** [comment]
I added you to the PS5 closed testing channel and tagged you in it, find the ping and type in that channel

**Comment by LightningMods** [comment]
since you are having issues ill go ahead and send you some links here for now (these are 1 time use links that expire in 10 mins)
https://justbeamit.com/bcccs
https://justbeamit.com/mmgkq

this new itemzflow pkg will print all the avail. DLCs you have for a given game to be sure everything works as PS4 before continuing

**Comment by ccfman2004** [comment]
When you sent me those links I wasn't even home.

**Comment by LightningMods** [comment]
Hello, disregard the last message for now, were you able to figure out discord and see where I pinged you in the server? If not done worry it's pretty simple once you get used to it

**Comment by ccfman2004** [comment]
I got into the channel and got the test etaHen and new Itemzflow.  I'll report back when after I try it out.

**Comment by ccfman2004** [comment]
I see that DLC support wasn't in the Itemzflow you posted on Discord. I was wondering why DLC wasn't being dumped.

**Comment by LightningMods** [comment]
Hello, yes ill send you a build that will print out all the DLC info to be sure its the same as on PS4 before moving forward, tag me on discord when you are available for that however that new itemzflow build has the new dumper so you can also test dumping the game you were talking about before

**Comment by LightningMods** [comment]
fixed in the newest itemzflow
