### ISSUE TITLE
zhtw translation not working, showing blank square texts

### ISSUE THREAD

**Issue by 29988122** [LightningMods/Itemzflow#37]
Bug description:
When using non english/non latin system language under 9.00 firmware ps4 with goldhen v24b16, itemzflow will not showing characters correctly.

Examples:
![image](https://github.com/LightningMods/Itemzflow/assets/5474709/86f46a9b-bfad-4a3f-b1d7-91b0bbce20c9)
![image](https://github.com/LightningMods/Itemzflow/assets/5474709/fb178956-58d6-467b-9c27-5e5821e7d746)

How to reproduce:
Use zh-tw as system language, install itemzflow from hb store v2.6 latest, and then install itemzflow v1.4.
Move to internal storage, and no text is displayed correctly.

Suggested bypass temp fix:
Default using English as interface language; prompt user to change language later in the options menu.

Proper fix:
After figuring out why the blank text bug, also add an menu option for users to choose language by themselves. (sometimes ppl can speak more than one language - and in the homebrew scene I think English is major, so defaulting English makes sense).

Thank you for your great work!!

**Comment by LightningMods** [comment]
Hello, the boxes mean the current font doesn't support the lang, you can try another ttf font that supports your lang via itemzflows advanced settings menu and lmk

**Comment by LightningMods** [comment]
Hello, let me know what font you ended up using and ill update itemzflow to use that font, I can add a lang override option to itemzflow next update however seeing if a font is compatible isn't really something I can do now as to the app nothing is wrong even if its not displaying the right characters

**Comment by 29988122** [comment]
Sure thing!
![image](https://github.com/LightningMods/Itemzflow/assets/5474709/6d8c7db0-5197-4c31-a6f1-7877dbc802e4)
![image](https://github.com/LightningMods/Itemzflow/assets/5474709/cdc25644-407a-4180-a035-5cdd8b30d60b)

Again, thanks for the great contribution to the homebrew scene : )
