### ISSUE TITLE
[Feature] - "Stream"/"Run" game from USB instead of NFS

### ISSUE THREAD

**Issue by treyus30** [LightningMods/Itemzflow#38]
Maybe I'm missing something, but a year ago you released an amazing service allowing streaming from an NFS, but not local storage. 

I would have assumed skipping the network and going straight from local storage would have come first, but this would be mean people would no longer have to keep two copies of their dumps. You would simply extract a pkg or dump to an exFAT drive and no actual install would ever be needed, and you wouldn't need to worry about extra network lag. 

To that end, my understanding is that there can only be one "app" selected at once, so ideally a folder and "remote play library" menu would be added too so a workaround to copy/paste the current app of interest doesn't need to be made.

**Comment by LightningMods** [comment]
Hello, I'm planning to add a such feature and will looking in it

**Comment by LightningMods** [comment]
Here's an update 
https://x.com/LightningMods_/status/1805742945703780526

**Comment by LightningMods** [comment]
This feature has been added to the new 1.06 update just released

**Comment by LightningMods** [comment]
@treyus30 sure lmk if you like it

**Comment by treyus30** [comment]
@LightningMods i can create a bug report, but what are the parameters required to use this? I select my pkg folder and am met with the error "Warning unable to open sce_sys/param.json OR sce_sys/param.sfo, did you select the right directory??"

**Comment by LightningMods** [comment]
@treyus30 the format is GAME_ROOT_FOLDER/sce_sys/param.sfo, GAME_ROOT_FOLDER/eboot.bin etc

**Comment by treyus30** [comment]
Where do these come from? Do I need to extract the each pkg?

**Comment by LightningMods** [comment]
@treyus30 yes you use it exactly how you would normally use NFS to run games just now you select the root game folder yourself manually
