### ISSUE TITLE
[Feature] Merge Game + Update

### ISSUE THREAD

**Issue by Nathan-MV** [LightningMods/Itemzflow#39]
It would be nice to have the option to always merge before installing and merge those already installed, showing the amount of space you will save before doing this would be wonderful

**Comment by LightningMods** [comment]
do you mean you want itemzflow to merge a game update to the base game pkg when you install it?

**Comment by Nathan-MV** [comment]
Unpacking the game and the update, and merging the two, creating a new pkg which will have reduced space, like pkgripper does
https://github.com/enriquesomolinos/pkgRipper
