### ISSUE TITLE
APP2USB

### ISSUE THREAD

**Issue by DragonLord7791** [LightningMods/Itemzflow#4]
AFTER BUILDING THE DATABASE WITH YOUR APPLICATION THE GAMES WHICH HAVE BEEN RUN BY APP2USB INTO THE EXTERNAL HARD DISK AND HAVE BROKEN SIMLINKS DON'T WORK ANYMORE. PLEASE FIND A SOLUTION FOR THE NEXT UPGRADE OF YOUR PROGRAM. HOPING THAT THE BROKEN APP2USB GAMES WITH SMLINK WILL WORK BACK. THANK YOU

**Comment by LightningMods** [comment]
I'll look into it

**Comment by DragonLord7791** [comment]
Hi,any news ? Thankyu

**Comment by LightningMods** [comment]
Try with this new update coming soon
