### ISSUE TITLE
[11.00/1.05] Crash while attempting to dump DLC

### ISSUE THREAD

**Issue by Izofeu** [LightningMods/Itemzflow#42]
Itemzflow version: 1.05
PS4 version: 11.00 slim
GoldHEN: v2.4b17.3
Itemzflow's crash code (PS4): CE-34878-0
Game that I attempted to dump: CUSA06211
Dumping option: DLC only
Itemzflow said that DLC aren't loaded and can't be dumped, so I started the game, attempted to load the DLC content, went back to itemzflow, tried to dump DLC only and itemzflow crashed immediately.
Steps to reproduce (crashes every time):
1. Open CUSA06211
2. Click around to make sure the game attempted to load DLC content
3. Go back to ps4 main menu
4. Open itemzflow (the game gets suspended)
5. Select Dump DLC only
6. Itemzflow shows "Starting the dumper" and crashes instantly

Note that selecting other dump options such as Dump Patch result in a successful dump.
If there are any log files that itemzflow generates, please let me know their path so I can send it here for further diagnosis.
![image](https://github.com/LightningMods/Itemzflow/assets/60717460/55c5d569-88ae-422e-b3b7-70fd2d1926f5)

**Comment by LightningMods** [comment]
Hello, ill look into it and provide an update soon

**Comment by LightningMods** [comment]
also before I forget, try to download the lastest itemzflow PKG and see if it gives you the option to upload the crash log when it crashes ,if not you can send me the logs from the itemzflow folder on your USB or /user/app/ITEM00001/logs

**Comment by Izofeu** [comment]
Attaching the log files from the PS4 internal drive:
[dumper.log](https://github.com/user-attachments/files/15859665/dumper.log)
[itemzflow_app.log](https://github.com/user-attachments/files/15859666/itemzflow_app.log)
[loader.log](https://github.com/user-attachments/files/15859667/loader.log)

**Comment by LightningMods** [comment]
good news, I was able to reproduce the crash and will be fixing it now, after ill send you a test PKG

**Comment by LightningMods** [comment]
@Izofeu try this PKG
[IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/user-attachments/files/15859821/IV0002-ITEM00001_00-STOREUPD00000000.zip)

**Comment by Izofeu** [comment]
> @Izofeu try this PKG [IV0002-ITEM00001_00-STOREUPD00000000.zip](https://github.com/user-attachments/files/15859821/IV0002-ITEM00001_00-STOREUPD00000000.zip)

The DLCs dumped just fine now! Thank you very much! ❤️
