### ISSUE TITLE
Itemzflow PS5 UI issues

### ISSUE THREAD

**Issue by ccfman2004** [LightningMods/Itemzflow#43]
I am having some UI issues on my 4.51 PS5.

1: Game covers go blank or weird colors
2. Some games aren't showing up
3. Sometimes a game title will say "App Title not found"
4. The UI will freeze and I cannot go back to Home. Holding the PS button doesn't work nor does pressing the PS button and selecting home. I can take a screenshot using the Share button and get back to home viewing that screenshot and then holding the PS button.

![Itemzflow Game Manager (PS5)_20240617114251](https://github.com/LightningMods/Itemzflow/assets/79392/e9fab602-b764-4076-8c2a-f838a1ccf41a)
[itemzflow_app.log](https://github.com/user-attachments/files/15873430/itemzflow_app.log)

**Comment by ccfman2004** [comment]
The UI at least in my short testing doesn't freeze when trying to Reload Apps. However the game covers still don't work.  They work, for the most part, when I scroll right. If I scroll left, no covers are displayed.  Also the game that wasn't showing up (Okage in my case) will show up sometime when the game list is reloaded but not always. Also game covers are REALLY broken if I have the list in Alphabetical order by Title Name which is how I prefer the list in so I can find the game I want to dump. With over 250 games in the list, when they are in Title ID order I have no idea where the game is the list. There really needs to be a better way of showing the installed games.

As a side note, I assume that game dumping was disabled for this test?

[itemzflow_app.log](https://github.com/user-attachments/files/15877001/itemzflow_app.log)

**Comment by LightningMods** [comment]
Hello, yes the new dumper requires an unreleased new version of etaHEN so it's practically disabled, I will look into the other issues tho

**Comment by LightningMods** [comment]
Here is another test PKG, rn im just testing things to see what improves it 
https://drive.google.com/file/d/1sF2QR6XHqu__N6McQXE4O_-wOMAHqbe-/view?usp=drive_link

**Comment by ccfman2004** [comment]
Here is a short video of what is going on. I didn't do a download of the latest covers. 

https://github.com/LightningMods/Itemzflow/assets/79392/004c266b-0ecb-4b55-b641-195fdacbb4a3

I don't suppose the new dumper will be able to decrypt PS4 exes?

**Comment by LightningMods** [comment]
the new dumper wont have an option to decrypt yet, I will follow up with you on this issue in a few days

**Comment by pixeltester** [comment]
> the new dumper wont have an option to decrypt yet, I will follow up with you on this issue in a few days

Hey LightningMods. I was looking to make an issue about this but since you mentioned it here it seems appropriate to just ask here.

I wanted to dump some of my legitimate PS4 games on the PS5 in order to create fake pkg backups for myself but I noticed various issues such as items needing to be decrypted (ok, there's other ways to do that), some files missing and files from the game's update being dumped in the base game files instead of the real base files (param, changeinfo and so on).

Is this something you will look at in the future? Thanks

**Comment by ccfman2004** [comment]
> > the new dumper wont have an option to decrypt yet, I will follow up with you on this issue in a few days
> 
> Hey LightningMods. I was looking to make an issue about this but since you mentioned it here it seems appropriate to just ask here.
> 
> I wanted to dump some of my legitimate PS4 games on the PS5 in order to create fake pkg backups for myself but I noticed various issues such as items needing to be decrypted (ok, there's other ways to do that), some files missing and files from the game's update being dumped in the base game files instead of the real base files (param, changeinfo and so on).
> 
> Is this something you will look at in the future? Thanks

Some game pkgs are what are called "Remasters" where the base amend updates are merged int one PKG. What games is this happening to?

**Comment by pixeltester** [comment]
No they aren't remasters, the dumper has these issues with any game.

**Comment by ccfman2004** [comment]
The PS5 version of Itemzflow doesn't decrypt anything yet.

**Comment by pixeltester** [comment]
Yes, as already mentioned. I was asking about the issues with the dumper as a whole as it seems you can't make proper dumps even with manual decryption at the moment.

**Comment by ccfman2004** [comment]
It just dawned on me that the one PS4 game I dumped and manually decrypted a while ago couldn't be made into a PKG.

**Comment by LightningMods** [comment]
Hello, Yes there will be a completely new dumper next itemzflow/etaHEN version, I ask that you wait until after it release to make new issues regarding the dumper

**Comment by Beyondf2** [comment]
Thanks, I'll check things out when the new dumper is released.

**Comment by pixeltester** [comment]
Thanks, I'll check things out when the new dumper is released.

**Comment by LightningMods** [comment]
@ccfman2004 Hello, after testing itemzflow on my PC with the clang leak sanitizer I noticed it was leaking image data when reloading the app list, I have now fixed that memory leak and hopefully your issue, let me know if you still face the same issue with this latest PKG

https://drive.google.com/file/d/1o9fWuycmG_SvqOz4J_-z0k26SMlupNTK/view?usp=sharing

**Comment by ccfman2004** [comment]
I have good new and bad news. The bad news is the issue still exists. The good news is I think I've narrowed down the issue. There seems to be a limit to how many covers Itemzflow can show without bugging out. 

With 95 items, there is no issue and everything seems to work correctly. With 100 items, the issue returns.  Hope that helps.

**Comment by LightningMods** [comment]
@ccfman2004 Here is another PKG to try, if the issue still exists send me the log 
https://drive.google.com/file/d/1AVl-yTJObTiliLjahCXtLlP99QO0wnjY/view?usp=sharing

**Comment by ccfman2004** [comment]
I went forward and backward several times with my 250+ game list. Closed the app and did that again and it all seems to be working just fine.  Only one slight issue with 2 PS5 games that show up as "App Title not found". Overcooked All You Can Eat and Worms Rumble.

As a side note, any chance of letting us choose between  12-hour and 24-hour clock. I grew up with the 12-hour clock and cannot read it to save my life.

If you need me to test anything else, let me know. Can't wait to try the new dumper. Hopefully it creates PS4 dumps that actually can be PKGed.

**Comment by LightningMods** [comment]
@ccfman2004 Im glad your orig. issue is fixed, for the other issue of some of the names not being found I would need to get the log again to look into that issue, here is another PKG that should have the time in 12-hour format

https://drive.google.com/file/d/1ags-dsOp-Ma8iR2NfBkB3EWTE0qiPKmd/view?usp=sharing

**Comment by ccfman2004** [comment]
Thanks. So much better now.

Any ETA on when the next etaHEN is coming out that supports the new Dumper? Can't wait to start dumping again.

**Comment by ccfman2004** [comment]
Sorry it took so long to get these logs. I completely forgot to get them.

These are the IDs of the 2 games.
```
Title ID: PPSA01527
Title ID: PPSA01529
```

[itemzflow_app.log](https://github.com/user-attachments/files/15951463/itemzflow_app.log)

**Comment by LightningMods** [comment]
Ill get back to this in a few days, just finishing up the PS4 update

**Comment by LightningMods** [comment]
@ccfman2004 Hello, I'm back now to look at the issue can you send me the 2 param.jsons for those games it fails to find the name for? normally it only fails to find the name if it doesnt have an en-US title so ill need to examine the files, also the New dumper will be coming out with the new PS5 itemzflow version hopefully sooner rather than later

**Comment by ccfman2004** [comment]
I hope these are the files you wanted. They were in the /user/appmeta folder.

All the games I have are the US versions as that is where I live.

Hope this helps.

Can't wait to try the new dumper. Hopefully it fixes the issue of PS4 dumps not being able to be made into a PKG.

[PPSA01527-param.json](https://github.com/user-attachments/files/16042642/PPSA01527-param.json)
[PPSA01529-param.json](https://github.com/user-attachments/files/16042643/PPSA01529-param.json)

**Comment by LightningMods** [comment]
try this new PKG and tell me if it fixes that issue for you
https://drive.google.com/file/d/1sSEfoz4SlMey1-5uWv2lAIzODusQPGcj/view?usp=sharing

**Comment by ccfman2004** [comment]
Both games now have their name displayed properly now.  Thanks.

What was the issue?

**Comment by LightningMods** [comment]
those games have no en-US titles in the json so now, instead of using en-US I have the app look for defaultLanguage which for those jsons was en-GB and then get that lang title

**Comment by ccfman2004** [comment]
I always seem to encounter the odd, weird bugs that nobody else has and the app developer can't easily reproduce.  At least now it should be fixed for everyone.
