### ISSUE TITLE
Failure to download game update

### ISSUE THREAD

**Issue by dazzaXx** [LightningMods/Itemzflow#44]
Hi, when attempting to download any update for Infinite Warfare (Disc - CUSA06448) I get this error.

Warning Install Failed with code
HEX: -0x7fbefec3 Int: -2143223491
sceBgftServiceIntDebugDownloadRegisterPkg

However I did notice the TID it's trying to download is CUSA05282.

EDIT: I'm using a PS4 Pro running 11.00 with PPPwn++

**Comment by LightningMods** [comment]
your internet/DNS is blocking the connection to Sonys server, that is what that error means
![image](https://github.com/LightningMods/Itemzflow/assets/34066913/f09291c8-e5a1-4d55-bd23-68405e017789)

**Comment by dazzaXx** [comment]
Ahh, that makes more sense. Thank you!

**Comment by dazzaXx** [comment]
One more thing sorry, what address would it be exactly? I believe the DNS setup on my pppwn device blocks multiple sony links.
