### ISSUE TITLE
[PS5] Duplicate VAPP impossible to remove

### ISSUE THREAD

**Issue by Cevati** [LightningMods/Itemzflow#49]
Hello dear LightningMods,

I tried a bit the PS5 FG feature but one game Destruction AllStars is not well recognized by Itemzflow and show as "App Title not found". I managed to make it launch properly but it appears in duplicate and can't be deleted (one I can launch and appear in game library which is deletable, the other one stay forever in game library).
When I say it can't be deleted is that going through Itemzflow "remove virtual app" doesn't do anything to this specific VAPP, refreshing still show this VAPP and I can always see it in my game library.
Also i updated to latest 1.06 Itemzflow (but i started having this duplicate issue with the old 1.06).
Is there a way to remove this dead link/icon?

Also thank you for all this, apart from this issue it's working really great!

**Comment by Cevati** [comment]
Added logs.
[itemzflow_app.log](https://github.com/user-attachments/files/16082519/itemzflow_app.log)
[loader.log](https://github.com/user-attachments/files/16082521/loader.log)

**Comment by LightningMods** [comment]
hello, for the first issue of the title not showing up, try this PKG (note this build has most features disabled as it requires the new etaHEN update which is not out yet so we will only be testing if the title shows up)

https://drive.google.com/file/d/1r20Imv3oDT08NLckfZqdI4hVyEW7wZCI/view?usp=sharing

**Comment by Cevati** [comment]
Re, this version of Itemzflow is very unstable, I get prompted with a lot of error messages of "IPC call failed, reboot your ps5 if this continues" when opening it, and it crashes if I try to refresh the app list, scan for ps5 dump or add it manually by path.

**Comment by LightningMods** [comment]
fixed in the latest itemzflow
