### ISSUE TITLE
Itemzflow wont boot off an external HDD

### ISSUE THREAD

**Issue by Neipas09** [LightningMods/Itemzflow#5]
PS4 Pro 9.00 / GoldHen 2.3 

Everytime i launch Itemzflow i get this error CE-34878-0
![image](https://user-images.githubusercontent.com/58871039/217896023-ca90e3f4-2b29-4bf9-b6d5-7707f43ae39f.png)

I've tried rebooting my PS4.
Installing it via the Homebrew Store.
Installing it via copy over FTP and then install from debug.

Homebrew store app works fine.
Games launch with no issues.
It's just this latest release is crashing every time i launch it.

**Comment by PaRaN01a-hash** [comment]
I'm having the same issue
9.00 GoldHen 2.3b1

**Comment by seba500plk** [comment]
Same, here log

[itemzflow_app.log](https://github.com/LightningMods/Itemzflow/files/10700881/itemzflow_app.log)

**Comment by LightningMods** [comment]
@seba500plk @Neipas09 @PaRaN01a-hash if you haven't already switch your language to English then tell me if it continues

**Comment by PaRaN01a-hash** [comment]
I'm already in English. From UK.

Tried with GoldHen 2.3 release as well but same common error number.

**Comment by LightningMods** [comment]
@PaRaN01a-hash if you can join my discord so I can try to find the issue https://discord.gg/fcUg6yP5Gy
you can also send me this log `/user/app/ITEM00001/logs/itemzflow_app.log`

**Comment by PaRaN01a-hash** [comment]
Hey mate

Attached is the log file
Hope that helps.

**Comment by LightningMods** [comment]
Hello @PaRaN01a-hash make sure Itemzflow is NOT installed to an external drive, currently IF only works if its on the internal drive

**Comment by Neipas09** [comment]
You can also try Deleting ItemzFlow's extra data using the GoldHen DELETE option.
![image](https://user-images.githubusercontent.com/58871039/217967355-9b1aaf8c-e0a1-4bb7-a2cd-9a1d4d25c731.png)

And using these options,
![image](https://user-images.githubusercontent.com/58871039/217967406-a466fc76-687a-4d62-9159-391ef3c0380e.png)

Then delete the app, and re-install it via the HomeBrew Store onto your Internal HDD.

Don't try installing it to an External HDD like I was doing... it doesn't work on there anymore for some reason :(

**Comment by seba500plk** [comment]
Moving app to internal storage fix the issue, thanks @Neipas09.

**Comment by LightningMods** [comment]
if that was @PaRaN01a-hash issue too I will close this

**Comment by PaRaN01a-hash** [comment]
Hey mate

Sorry for late reply, just woke up this end.


So delete off extended and installed on internal.
Working a treat now. Thank you for your help mate. Means a lot
