### ISSUE TITLE
Fake Game support on PS5

### ISSUE THREAD

**Issue by Cybereu** [LightningMods/Itemzflow#51]
_Fake Game support (load dumps from USB or local storage, supports NFS, requires external fake signing)_

Feature added on lastest update (1.06) dos not show on PS5 version of homebrew.

**Comment by LightningMods** [comment]
the Fake game feature is the same feature people have been using to play dumped PS5 games on PS5 just under a different name

**Comment by Cybereu** [comment]
I understand. However, I'd like to link PS4 games to my PS5 through the app. The actual app only seems to allow linking dumped PS5 games.
