### ISSUE TITLE
NFS support for 9.0.3?

### ISSUE THREAD

**Issue by seathasky** [LightningMods/Itemzflow#52]
on hen-vtx on fw 9.03 and NFS doesnt work for me. Any fix for this?

**Comment by LightningMods** [comment]
What is the issue you are facing? Does it just give you a connection error or does it panic your console?

**Comment by seathasky** [comment]
Stuck at "Connecting to NFS Share" times out after a couple minutes with
"error: network share failed to connect" ret: -5

I don't use firewalls on PC or router. Using latest winnfsd

**Comment by seathasky** [comment]
Here's how I have it set up. I've tried -addr and my pcs IP as well.
![image](https://github.com/user-attachments/assets/7a44c3b8-d182-4d40-a6c1-8cf893764911)

**Comment by seathasky** [comment]
Of course it starts working after I put in a ticket. thanks for reaching out. NFS does work on 9.03
