### ISSUE TITLE
NFS Multiple Apps

### ISSUE THREAD

**Issue by Gouster4** [LightningMods/Itemzflow#54]
Hello. As far as I noticed, NFS share is able to load single app extracted in NFS share.
Is there a way to mount NFS share in place of game directory, so multiple games/apps Can be loaded from NFS, and also new packages will be installed to NFS instead of internal HDD?

Thank you.

**Comment by LightningMods** [comment]
Yes, you do it the same way, like the change log says
- Added (experimental) Fake Game support (load dumps from USB or local storage, **supports NFS**, requires external fake signing)

refer to this tweet where I run multiple NFS apps via the Fake Game option
https://x.com/LightningMods_/status/1806508635595686128

**Comment by Gouster4** [comment]
That is awesome. I guess I got the point...
Sorry for re-opening, just want to ask last question.
Is it possible to install packages directly on PS4 to NFS?
Or is it at least planned for future?

Thank you.
