### ISSUE TITLE
Cannot open file G:\CUSA08692\playgo-chunks.xml 

### ISSUE THREAD

**Issue by DiverseBloom780** [LightningMods/Itemzflow#57]
dumping CUSA08692 - Dark Souls Remastered today and the fpkg tools gave me this error, is it something with itemzflow doing this?

**Comment by LightningMods** [comment]
I don't think so as that XML file shouldn't even be in the root folder and Itemzflow dumps that file to the sce_sys folder so I'm not even sure why that XML file is in the root folder

**Comment by DiverseBloom780** [comment]
> I don't think so as that XML file shouldn't even be in the root folder and Itemzflow dumps that file to the sce_sys folder so I'm not even sure why that XML file is in the root folder, ill need more info as to what your issue is

tried to create a .gp4 with Cyber1k fpkg tools and that was the error that popped up, and sure enough thet .xml is there in the root 
![Desktop Screenshot 2024 08 08 - 16 43 22 16](https://github.com/user-attachments/assets/10efdd62-adc7-422d-a0ef-d1db4babbc4b)
![Desktop Screenshot 2024 08 08 - 16 46 54 70](https://github.com/user-attachments/assets/2cfdbd5c-bd21-4fd4-ae4d-898c7d3176f7)

**Comment by LightningMods** [comment]
try moving it to the sce_sys folder and try again

**Comment by DiverseBloom780** [comment]
> try moving it to the sce_sys folder and try again

i will try and see what happens after that

**Comment by LightningMods** [comment]
What are the issues with those games? I know for TLOUS2 the dumper will get stuck if not all the games languages are installed

**Comment by DiverseBloom780** [comment]
> What are the issues with those games? I know for TLOUS2 the dumper will get stuck if not all the games languages are installed

TLOU2 i was stuck with something with the .png not being transparent along with Far Cry Primal giving me the same problems, i unfortunately am not someone experienced with photo software and couldn't get anyone locally to help me with it, so had to get a repack from somewhere else, God Of War 2018 i could not get to dump for the life of me, i tried what Modded Warfare said to do was to delete bdcopy.pbm and it still refused to dump, even tho it said it was dumping the disc files, i would check it aftterwards and there would be a incomplete dump or nothing there at all, so i had to get a repack of that from somewhere as well,i have not tried dumping them again until i tried dumping Dark Souls Remastered, i forgot the last time i dumped it, the things had given me this issue before

**Comment by LightningMods** [comment]
the image issue isnt an issue with the dumper however its super easy to fix using online photo editors, as for GOW that sounds strange and I would need the log to look into it, can you build the PKG using the GP4 itemzflow generates for you instead?

**Comment by DiverseBloom780** [comment]
> the image issue isnt an issue with the dumper however its super easy to fix using online photo editors, as for GOW that sounds strange and I would need the log to look into it, can you build the PKG using the GP4 itemzflow generates for you instead?

i have not tried letting it create the .gp4 for me, i can try that  here in awhile with it, which game ya want me to try?

**Comment by LightningMods** [comment]
@DiverseBtry with dark souls

**Comment by DiverseBloom780** [comment]
> @DiverseBtry with dark souls

alright i will try again in a bit to see what happens

**Comment by DiverseBloom780** [comment]
> @DiverseBtry with dark souls

Death Stranding v1.13 Dumper gets stuck at 32% and does not go any further, i have left it running since 12:00pm and i just check it now at 5:50pm an it was still stuck, so i restarted it again, it got stuck on a .bin file

**Comment by LightningMods** [comment]
@DiverseBloom780 
The readme mentions this and so does issue #45, this is nothing new, even in modded warfare's tutorials he mentions this

https://github.com/LightningMods/Itemzflow?tab=readme-ov-file#dumper-details

If you read the readme you would know it gets stuck on files that are not installed like additional language packs, that bin file likely also tells you the lang in the filename

**Comment by DiverseBloom780** [comment]
> @DiverseBloom780 The readme mentions this and so does issue #45, this is nothing new, even in modded warfare's tutorials he mentions this
> 
> https://github.com/LightningMods/Itemzflow?tab=readme-ov-file#dumper-details
> 
> If you read the readme you would know it gets stuck on files that are not installed like additional language packs, that bin file likely also tells you the lang in the filename

there is no language packs for that game or TLOU2, i just looked on the store in the add ons for it

**Comment by LightningMods** [comment]
@DiverseBloom780 there is lang packs for TLOUS2 that's the 1 game I know for a fact has lang packs and modded warfare mentioned that game spec. in his video, its the same with cyberpunk too https://github.com/LightningMods/PS4-Store/issues/16

![image](https://github.com/user-attachments/assets/63961504-eefb-4705-950d-05357c12fc3d)

but if you think you know more than the person that **made** itemzflow just keep downloading the games instead of dumping them, i'll lose no sleep at night
