### ISSUE TITLE
Itemzflow 1.06 crashes PS4 Pro on 11.0fw when closing application

### ISSUE THREAD

**Issue by DiverseBloom780** [LightningMods/Itemzflow#58]
my PS4 keeps crashing everytime i close Itemzflow 1.06

**Comment by LightningMods** [comment]
Are you closing the app via pressing circle twice in the app? If you are not thats why it's there, don't exit through the ps4s menu only from in the app

**Comment by DiverseBloom780** [comment]
> Are you closing the app via pressing circle twice in the app? If you are not thats why it's there, don't exit through the ps4s menu only from in the app

oh okay i did not know that, sorry about that, i was not informed about that
