### ISSUE TITLE
NFS server on linux, failed to connect

### ISSUE THREAD

**Issue by remlei** [LightningMods/Itemzflow#6]
For some reason it fails to connect but works fine if I use the WinNFSd on windows.

My suspect is itemflowz is connecting using v3 protocol and WinNFSd apparently is only v3 supported but nfs server on linux on reliably works on v4.1

**Comment by LightningMods** [comment]
Itemzflow supports both NFS v3 and v4, however, for Linux you may need to type in NFS format
for example `nfs://192.1.2.3/share_name`

if that doesn't work send me these logs
`/user/app/ITEM00001/logs/itemzflow_app.log`
`/data/itemzflow_daemon/daemon.log`

**Comment by remlei** [comment]
thanks for the reply. already check the logs and it seems that its a permission issue.. 

2023-02-10 08:49:59 DEBUG source/fuse-nfs.c:964: [ItemzDaemon]String is in NFS format.
2023-02-10 08:49:59 INFO  source/fuse-nfs.c:971: [ItemzDaemon]NFS [nfs://192.168.254.2/test]
2023-02-10 08:49:59 ERROR source/fuse-nfs.c:989: [ItemzDaemon]Failed to mount nfs share : mount_cb: RPC error: Mount failed with error MNT3ERR_ACCES(13) Permission denied(13)
2023-02-10 08:49:59 ERROR source/fuse-nfs.c:1009: [ItemzDaemon]Failed to mount nfs share : -13


tried it with synolofy with DSM7, cant connect
tried it with OMV with NFS server shares option (insecure, insecure_locks, no_auth_nlm, no_root_squash, no_subtree_check, rw) still cant connect 

any suggestions?

**Comment by LightningMods** [comment]
According to my research

```
This is not a libnfs issue but a problem with your servers configuration.

Your server is returning NFS3ERR_ACCES which means that you have not set up the permissions properly on the server.

You need to set these shares up to allow "nobody" (uid 65534) permissions to read the directory.

As windows does not traditionally have a unix uid assigned to the current user, libnfs and the utilities will default to use uid 65524 for all I/O.
You can override this and use a specific uid by appending &uid=1234 to the nfs url, If that is the uid you want to use.
```

**Comment by remlei** [comment]
Thats true but that what no_root_squash should be able to resolve, basically give everything root priveledge to the share.

But hey i still tried adjusyibg the permission but still same issue.

**Comment by LightningMods** [comment]
I'm not sure what the issue is then, personally, I have only tried WinNFSd and Windows server 2019 (with built-in NFS features) both worked but I know Linux can sometimes be tricky to get things to work unlike Windows server that just gives you everything in a user-friendly setup wizard

besides that, I have seen some people say libnfs works as root but I'm not sure if that's the issue, Ill leave this open until someone finds a workaround or you fix it

**Comment by remlei** [comment]
Linux is quite strict with tgis stuff, it requires extra param for uid and gid for the share. I dont kbow how nfs client on your app works unless this was able to be added, i dont think any NAS nfs share will work here.

**Comment by LightningMods** [comment]
I'm using this lib for NFS https://github.com/orbisdev/orbisdev-liborbisNfs
and I'm using this with Fuse https://github.com/sahlberg/fuse-nfs

Hopefully that give you an idea

**Comment by remlei** [comment]
was able to figure out the issue, the mountpoint is actually wrong (my fauls) it needs to appens /export and then the share name after that (nfs://1.2.3.4/export/share_name), still the issue persist with synology NFS server (nothing you can do about it, it really requires uid/gid even for unrestricted guest access) was able to work around it with a docker container.

**Comment by Sylntnyt** [comment]
@remlei I'm on Linux (Ubuntu 20.04) all the tutorials I've seen on how to set up the NFS server on the computer say the same thing which I followed to a "T" and I'm interested in what guide you followed and also wanted clarification on your fix so I can see if it will fix my issue of my PS4 not connecting to the server.
