### ISSUE TITLE
Move DLC content from internal HDD to external does not work on PS4

### ISSUE THREAD

**Issue by Sepalod** [LightningMods/Itemzflow#61]
I immediately receive the notification "Failed to move" for DLC content. Moving apps and patches, on the other hand, works without any problems.
Could there also be a function that turns off the check after a move if desired?

**Comment by LightningMods** [comment]
when you get that error upload the log via itemzflow settings and let me know when you have done that and ill look into this issue

**Comment by LightningMods** [comment]
closed for inactivity as stated in the readme
