### ISSUE TITLE
Move to USB function crashes Itemzflow

### ISSUE THREAD

**Issue by aanderson2040** [LightningMods/Itemzflow#64]
Everything works fine (there's still the occasional crash when clicking on games) but my main issue is whenever I try to click on "Move to USB" it crashes 90% of the time. I have to close and reopen the app around 5 times just to be able to backup one game to USB. 

Is there a better way to do this that doesn't involve using Sony's built in backup tool? I'm hoping to utilize my 12TB to its max capacity and the Sony built in one only allows 8TB.

**Comment by LightningMods** [comment]
when it crashes be sure you have internet then press yes when it asks you to upload the crash log, if it didn't give you the option dony worry bc itemzflow keeps the last 3 app logs and in that case go to itemzflow's settings and press triangle to upload the logs

**Comment by aanderson2040** [comment]
Never mind it must've been a WiFi issue! Sorry I never thought to try connecting it to the internet but everything looks to be working perfectly fine surprisingly now.
