### ISSUE TITLE
Kingdom Hearts III incorrect display name

### ISSUE THREAD

**Issue by ccfman2004** [LightningMods/Itemzflow#65]
Itemzflow displays Kingdom Hearts III incorrectly with the III being treated as a single character which gets displayed as a square.

The logs confirm that the III is being treated as a single character when you go to highlight it for some reason.

I assume this should be easy to fix.

![Itemzflow Game Manager_20240904200005](https://github.com/user-attachments/assets/3a92e1ba-5c99-460a-afef-fa256d55d32a)
[itemzflow_app.log](https://github.com/user-attachments/files/16882272/itemzflow_app.log)

**Comment by Masamune3210** [comment]
I'm assuming the title uses the actual ASCII character representation of the roman numeral three instead of just doing three I's like most people do, and the font doesn't support that particular character, which is why its showing as the Unicode Character not Found box

**Comment by LightningMods** [comment]
Like the other guy said it's likely not supported by the font, you can test this by going into Itemzflows settings menu and change the font under advanced settings, let me know if a different font fixes your issue

**Comment by ccfman2004** [comment]
Where do I find another font in the system? Where is the font the home menu uses?

**Comment by LightningMods** [comment]
@ccfman2004 you should be able to find other fonts in itemzflows sandbox (/mnt/sandbox/...) in the `assets/fonts` folder, also anything a font doesnt recognize is a box and 3 Roman numerals together is likely just 1 word to the font, so I, II, III are all 1 character

**Comment by ccfman2004** [comment]
I see 2 fonts in that directory and neither one fixes the box issue.

**Comment by Masamune3210** [comment]
> @ccfman2004 you should be able to find other fonts in itemzflows sandbox (/mnt/sandbox/...) in the `assets/fonts` folder, also anything a font doesnt recognize is a box and 3 Roman numerals together is likely just 1 word to the font, so I, II, III are all 1 character

If its a Unicode-compliant font, Roman Numerals are indeed single glyphs per number and are stored at U+2160-U+2188 as part of a grouping involving other numeric representations

![image](https://github.com/user-attachments/assets/08bdb624-225c-43b1-b9f5-6831fa276e09)

**Comment by Masamune3210** [comment]
Sidenote, the only reason this exists (and this is outlined in that pic of Wikipedia) is that Asian texts tend to use the combined forms so that they appear correctly when written next to Katakana or whatever writing system is being used that is non-Latin
