### ISSUE TITLE
Itemzflow UI is not responsive

### ISSUE THREAD

**Issue by spacevx** [LightningMods/Itemzflow#73]
Hello the UI is not responsive, im on a TV screen and here is the result
![image](https://github.com/user-attachments/assets/f0bb8d1c-0dac-4105-8d4f-6a562dff1b55)![Uploading 373888081...]![image](https://github.com/user-attachments/assets/7aae3787-576d-434e-848d-3e2a51c34b2e)

**Comment by LightningMods** [comment]
Is it still unresponsive without the theme? I identified an issue causing it to constantly try to load images from the theme that don't exist in older themes like the one you have on

**Comment by LightningMods** [comment]
Hello, I'm currently working on optimizing performance for the next update, stay tuned

**Comment by LightningMods** [comment]
closing due to inactivty
