### ISSUE TITLE
ERROR: Network Share failed to connect check your connection and try again

### ISSUE THREAD

**Issue by iceMongus** [LightningMods/Itemzflow#8]
on windows 11 
                         WinNFSd.exe -addr 10.10.1.16 K:\PlayStation\PS4\!Packages\ 
share is accessible "CHECKED" !!

on PlayStation 4 PRO with IP 10.10.1.50
         ERROR: Network Share failed to connect check your connection and try again 
         ret:243

in WinNFSd.exe console
                    Port map daemon started
                    NFS daemon started
                    Mount daemon started
                    Listening on 10.10.1.16
                    Type 'help' to see help

                    PORTMAP NULL
                    PORTMAP GETPORT 100005 1058
                    MOUNT NULL
                    MOUNT MNT from 10.10.1.50
                    Final local requested path:

where is the problem ???

trying to connect PS4 to nas NFS share and ... the same ???
user and pass pass disabled on NFS share NON-root access is set

**Comment by Scalerize** [comment]
Same thing here, but if modded warfare is able to do it, i believe it might be a noobie mistake on our side.

**Comment by Scalerize** [comment]
> 

I had he same issue, it's because you forgot to add a "/" at the end of your directory in the .bat file

Example:

instead of "C:\Users\USERNAME\Desktop\PS4SHARE\app" 

you use "C:\Users\USERNAME\Desktop\PS4SHARE\app" /

**Comment by remlei** [comment]
I also had this issue at first when troubleshooting issue with NFS connection to my NAS, ended up this issue is related to wsl and/or hyperv

you can try enter this command in command prompt with elevated priveledge 

`net stop winnat
net start winnat`

reference: https://github.com/docker/for-win/issues/3171

**Comment by iceMongus** [comment]
with / and without / the same shit !!!!

**Comment by LightningMods** [comment]
This issue has closed as WinNFSd has nothing to do with Itemzflow, if you have an issue with WinNFSd I recommend making an issue with them here https://github.com/winnfsd/winnfsd/issues, alternatively, you can try the other many paid NFS solutions for windows or try with an OS with native NFS features
